### ISSUE TITLE
Seat v5

### ISSUE THREAD

**Issue by Wertster** [cryocaustik/seat-hr#14]
Is there any plan for a version of SeatHR for Seat 5? Thanks

**Comment by cryocaustik** [comment]
SeAT v5 is already supported under the [v2.x branch](https://github.com/cryocaustik/seat-hr/tree/v2.x) - I am updating the readme/instructions to better reflect that

**Comment by Wertster** [comment]
Awesome thanks On 13 Mar 2024, at 14:49, Alex Skobelev ***@***.***> wrote:﻿
SeAT v5 is already supported under the v2.x branch - I am updating the readme/instructions to better reflect that
